# Generated by Django 6.0 on 2026-01-11 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('prescriptions', '0002_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentfile',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_files', to='appointments.appointment'),
        ),
    ]
